# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 21:30
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190220_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/lrx/bookstore/collect_static'), upload_to='books', verbose_name='商品图片'),
        ),
    ]
