# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-18 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderGoods',
            new_name='OrderBooks',
        ),
    ]
